"""All game content: prompts, questions, words, categories, etc."""

import random
from typing import Any

# ─── Truth or Dare ───────────────────────────────────────────────────────────

TRUTHS = [
    "What's the most embarrassing thing you've done while drunk?",
    "What's the worst text you've ever sent to the wrong person?",
    "What's the biggest lie you've told to get out of plans?",
    "Who in this room would you least want to be stuck on an island with?",
    "What's the most ridiculous thing you've done to impress a crush?",
    "What's the weirdest thing you've Googled recently?",
    "What's a secret you've never told anyone in this room?",
    "What's the pettiest reason you've stopped talking to someone?",
    "If you could read one person's mind in this room, who would it be?",
    "What's the most cringe thing in your camera roll right now?",
    "What's the dumbest thing you've spent money on while drunk?",
    "Who was your worst kiss and why?",
    "What's your most embarrassing autocorrect fail?",
    "What's a red flag you totally ignored in a relationship?",
    "What's the longest you've gone without showering?",
    "What's the most childish thing you still do?",
    "Who in this room do you think is the worst driver?",
    "What's the worst date you've ever been on?",
    "What's the most awkward thing that happened to you at work/school?",
    "Have you ever pretended to be sick to avoid someone? Who?",
    "What's the most questionable thing in your search history?",
    "If your browser history was made public, what would be most embarrassing?",
    "What's a guilty pleasure you're embarrassed to admit?",
    "Who was the last person you stalked on social media?",
    "What's the most ridiculous excuse you've made up?",
    "What's something you've done that you'd judge someone else for?",
    "What's the worst gift you've ever received and pretended to like?",
    "Have you ever had a crush on a friend's partner?",
    "What's the most embarrassing thing your parents caught you doing?",
    "What's your most irrational fear?",
    "What's the most trouble you've ever gotten into with your parents?",
    "Have you ever pretended to like a gift so hard it became a whole lie?",
    "What's the pettiest thing you've ever done to an ex?",
    "What's the most illegal thing you've done and gotten away with?",
    "If you had to delete one app off your phone forever, which would it be?",
    "What's the meanest thing you've said behind someone's back?",
    "Have you ever cried in public over something embarrassing?",
    "What's the dumbest hill you're willing to die on?",
    "What's a trend you followed that you now deeply regret?",
    "What's the longest you've kept a secret from the group?",
    "Who in this room would you swap lives with for a week?",
    "What's the most unhinged thing you've done at 3am?",
    "Have you ever lied about liking someone's cooking?",
    "What's the most embarrassing song on your most-played list?",
    "If your friends could see your notes app, what would shock them most?",
]

DARES = [
    "Take a sip and do your best impression of someone in the room.",
    "Let the group go through your last 10 photos. Take a sip for each embarrassing one.",
    "Call a random contact and sing Happy Birthday. Drink if they hang up.",
    "Post the 3rd last photo in your camera roll on your story for 1 hour or drink twice.",
    "Let someone in the group send a text from your phone. Drink regardless.",
    "Do your best drunk celebrity impression for 30 seconds.",
    "Talk in an accent for the next 3 rounds or take 2 sips.",
    "Give a dramatic 30-second speech about why pineapple belongs on pizza.",
    "Let the group pick your profile picture for 24 hours or drink 3 times.",
    "Dramatically reenact the last argument you had.",
    "Speak in only questions for the next 2 rounds. Drink when you fail.",
    "Give a compliment to everyone in the room. Drink for each awkward pause.",
    "Tell the room your most used emoji and explain why. Drink if it's embarrassing.",
    "Do your best TikTok dance. Drink twice if nobody recognizes it.",
    "Read your last sent text out loud to the group.",
    "Let the person to your right post anything they want on your social media.",
    "Serenade the person across from you with a love song.",
    "Talk without closing your mouth for 30 seconds. Drink if you fail.",
    "Share the last thing you copied on your clipboard.",
    "Give a 1-minute motivational speech about something completely mundane.",
    "Act out a movie scene and everyone has to guess. Drink if nobody gets it.",
    "Say something nice about every person in the room in a baby voice.",
    "Demonstrate your signature dance move. Everyone drinks if it's bad.",
    "Attempt to beatbox for 15 seconds. Drink if you can't keep a beat.",
    "Tell the group your screen time for this week. Drink for every hour over 4.",
    "Let the group write a text and send it to your most recent contact.",
    "Do your best impression of a crying baby for 20 seconds.",
    "Speak in a whisper for the next 3 rounds or take 3 sips.",
    "Show your most embarrassing saved reel or TikTok to the group.",
    "Let the group pick a song — you must sing the chorus with full emotion.",
    "Tell the group your most embarrassing nickname and how you got it.",
    "Give a 30-second roast of the person to your left. Keep it friendly.",
    "Do your best runway walk across the room. Everyone rates you 1-10.",
    "Call a random contact and ask them if they believe in aliens. Speaker on.",
    "Hold an ice cube in your hand until it melts or take 4 sips.",
    "Let the group go through your Spotify Wrapped or most-played. Drink for each guilty pleasure.",
    "Make up a rap about the person across from you. 30 seconds minimum.",
    "Put your phone on speaker and call your voicemail. Play any saved messages out loud.",
    "Text your mom 'I have something important to tell you' and wait for the response on speaker.",
]

# ─── Never Have I Ever ───────────────────────────────────────────────────────

NEVER_HAVE_I_EVER = [
    "Never have I ever sent a drunk text I deeply regret",
    "Never have I ever pretended to be someone else online",
    "Never have I ever eaten food off the floor",
    "Never have I ever lied on my resume",
    "Never have I ever ghosted someone",
    "Never have I ever cried at a movie in the theater",
    "Never have I ever been kicked out of a bar",
    "Never have I ever faked being sick to skip work/school",
    "Never have I ever re-gifted a present",
    "Never have I ever stalked an ex on social media",
    "Never have I ever gone skinny dipping",
    "Never have I ever forgotten someone's name right after meeting them",
    "Never have I ever accidentally liked a very old Instagram post while stalking",
    "Never have I ever broken something at someone's house and not told them",
    "Never have I ever walked into a glass door",
    "Never have I ever peed in a pool as an adult",
    "Never have I ever taken something from a hotel room",
    "Never have I ever pretended to laugh at a joke I didn't get",
    "Never have I ever been caught talking to myself",
    "Never have I ever had a wardrobe malfunction in public",
    "Never have I ever eaten an entire pizza by myself in one sitting",
    "Never have I ever forgotten a significant other's birthday",
    "Never have I ever tripped in public and pretended nothing happened",
    "Never have I ever read someone's messages without permission",
    "Never have I ever blamed a fart on someone else",
    "Never have I ever clogged someone else's toilet",
    "Never have I ever lied about my age",
    "Never have I ever watched a kids' show as an adult and enjoyed it",
    "Never have I ever been so hungover I swore I'd never drink again",
    "Never have I ever accidentally called a teacher 'mom' or 'dad'",
    "Never have I ever taken a selfie in the bathroom",
    "Never have I ever eaten something that fell in the sink",
    "Never have I ever had an imaginary friend past age 10",
    "Never have I ever worn the same underwear two days in a row",
    "Never have I ever waved back at someone who wasn't waving at me",
    "Never have I ever pretended to be on the phone to avoid someone",
    "Never have I ever Googled myself",
    "Never have I ever cried because of a song",
    "Never have I ever stayed in bed all day watching TV",
    "Never have I ever been to a psychic or fortune teller",
    "Never have I ever left a store without buying anything and felt guilty",
    "Never have I ever finished an entire Netflix series in one day",
    "Never have I ever lied about finishing a book or show to fit in",
    "Never have I ever danced alone in my room like nobody was watching",
    "Never have I ever laughed so hard I peed a little",
    "Never have I ever made up an excuse to leave a party early",
    "Never have I ever eaten someone else's food from the fridge",
    "Never have I ever pretended to know a song and hummed along",
    "Never have I ever tripped going UP the stairs",
]

# ─── Would You Rather ────────────────────────────────────────────────────────

WOULD_YOU_RATHER = [
    ("Always have to speak in rhymes", "Always have to speak in song lyrics"),
    ("Have no filter for one full day", "Have everyone read your thoughts for one hour"),
    ("Give up your phone for a month", "Give up your bed for a month"),
    ("Be famous but always broke", "Be rich but nobody knows your name"),
    ("Relive high school", "Skip ahead to being 70"),
    ("Only eat one meal a day forever", "Never eat your favorite food again"),
    ("Have a rewind button for your life", "Have a pause button"),
    ("Know when you're going to die", "Know how you're going to die"),
    ("Fight 100 duck-sized horses", "Fight 1 horse-sized duck"),
    ("Always be 10 minutes late", "Always be 20 minutes early"),
    ("Lose the ability to read", "Lose the ability to speak"),
    ("Be able to fly but only 2 feet off the ground", "Be invisible but only when nobody's looking"),
    ("Have a permanent clown face", "Have a permanent clown laugh"),
    ("Have hands for feet", "Have feet for hands"),
    ("Always smell slightly like onions", "Always have a booger visible in your nose"),
    ("Give up Netflix forever", "Give up Spotify forever"),
    ("Have unlimited money but no friends", "Be broke but have the best friends"),
    ("Be allergic to your phone", "Be allergic to your favorite drink"),
    ("Always feel like you have to sneeze", "Always have a song stuck in your head"),
    ("Eat a tablespoon of hot sauce before every meal", "Drink a glass of pickle juice every morning"),
    ("Have everyone know your browser history", "Have everyone know your bank account balance"),
    ("Be stuck in an elevator with your ex", "Be stuck in an elevator with your boss"),
    ("Only whisper for the rest of your life", "Only shout for the rest of your life"),
    ("Give up social media forever", "Give up desserts forever"),
    ("Have a third eye on the back of your head", "Have an extra mouth on your forehead"),
    ("Be able to taste colors", "Be able to hear smells"),
    ("Have free WiFi everywhere but it's always slow", "Have the fastest WiFi but only at home"),
    ("Accidentally reply-all to a company email with a meme", "Accidentally post a selfie to your work Slack"),
    ("Have your life narrated by Morgan Freeman", "Have your life narrated by a sports commentator"),
    ("Only be able to eat gas station food", "Only be able to drink hotel coffee"),
    ("Have your Spotify Wrapped made public every week", "Have your screen time made public every week"),
    ("Win $50k but have to spend it in one day", "Win $500 every month forever"),
    ("Always have wet socks", "Always have an eyelash in your eye"),
    ("Be the funniest person alive but nobody laughs at your jokes", "Never be funny but everyone always laughs at you"),
    ("Go back in time to fix one embarrassing moment", "Skip forward to see one day of your future"),
    ("Accidentally fart in every job interview", "Accidentally burp in every first date"),
    ("Have a personal theme song that plays everywhere you go", "Have a laugh track that plays after everything you say"),
    ("Only communicate through memes for a week", "Only communicate through song lyrics for a week"),
    ("Wake up in a new random country every morning", "Relive the same perfect day forever"),
]

# ─── Kings Cup Card Rules ────────────────────────────────────────────────────

KINGS_CUP_RULES: dict[str, dict[str, str]] = {
    "A":  {"name": "Waterfall",        "rule": "Everyone starts drinking. You can only stop when the person before you stops."},
    "2":  {"name": "You",              "rule": "Pick someone to drink."},
    "3":  {"name": "Me",               "rule": "You drink."},
    "4":  {"name": "Floor",            "rule": "Last person to touch the floor drinks."},
    "5":  {"name": "Guys",             "rule": "All guys drink."},
    "6":  {"name": "Chicks",           "rule": "All ladies drink."},
    "7":  {"name": "Heaven",           "rule": "Last person to raise their hand drinks."},
    "8":  {"name": "Mate",             "rule": "Pick a drinking buddy. They drink whenever you drink."},
    "9":  {"name": "Rhyme",            "rule": "Say a word. Go around rhyming it. First person who can't rhyme drinks."},
    "10": {"name": "Categories",       "rule": "Pick a category. Go around naming things in it. First person who repeats or blanks drinks."},
    "J":  {"name": "Rule Master",      "rule": "Make a rule everyone must follow. Anyone who breaks it drinks."},
    "Q":  {"name": "Question Master",  "rule": "You're the Question Master. Anyone who answers your questions drinks — until the next Queen is drawn."},
    "K":  {"name": "King's Cup",       "rule": "Pour some of your drink into the King's Cup. Whoever draws the 4th King drinks it all."},
}

SUITS = ["spades", "hearts", "diamonds", "clubs"]
SUIT_SYMBOLS = {"spades": "\u2660", "hearts": "\u2665", "diamonds": "\u2666", "clubs": "\u2663"}

# ─── Most Likely To ──────────────────────────────────────────────────────────

MOST_LIKELY_TO = [
    "Most likely to get lost in their own neighborhood",
    "Most likely to survive a zombie apocalypse",
    "Most likely to accidentally start a fire",
    "Most likely to become famous for something embarrassing",
    "Most likely to show up to the wrong event",
    "Most likely to fall asleep first at a party",
    "Most likely to marry a celebrity",
    "Most likely to text their ex tonight",
    "Most likely to get arrested for something stupid",
    "Most likely to cry during a commercial",
    "Most likely to go viral on social media",
    "Most likely to spend their rent money on something dumb",
    "Most likely to get into an argument with a stranger",
    "Most likely to forget their own birthday",
    "Most likely to talk their way out of a speeding ticket",
    "Most likely to win a hot dog eating contest",
    "Most likely to become a conspiracy theorist",
    "Most likely to accidentally join a cult",
    "Most likely to go on a reality TV show",
    "Most likely to get banned from a restaurant",
    "Most likely to adopt 10 cats",
    "Most likely to laugh at the worst possible time",
    "Most likely to bring up an embarrassing story in public",
    "Most likely to eat something off the ground",
    "Most likely to send a risky text and immediately regret it",
    "Most likely to have a secret talent nobody knows about",
    "Most likely to get into a fight over food",
    "Most likely to be the loudest person in any room",
    "Most likely to wake up in a completely different city",
    "Most likely to accidentally offend someone without realizing it",
    "Most likely to start a podcast nobody listens to",
    "Most likely to cry at their own wedding speech",
    "Most likely to get famous from a mugshot",
    "Most likely to reply-all to a company email by accident",
    "Most likely to get into a fight over a parking spot",
    "Most likely to take the longest to get ready",
    "Most likely to still use Facebook in 2030",
    "Most likely to ghost a therapist",
    "Most likely to accidentally set off a fire alarm",
    "Most likely to lie about having read a book",
    "Most likely to get scammed by a Nigerian prince",
    "Most likely to eat something off a stranger's plate",
    "Most likely to cry if their phone battery dies",
    "Most likely to leave the house without pants and not notice",
]

# ─── Categories ──────────────────────────────────────────────────────────────

CATEGORIES = [
    "Types of beer",
    "Cocktail names",
    "Things you'd find in a bar",
    "Excuses for being late",
    "Things you shouldn't say to your boss",
    "Fast food chains",
    "Things that are green",
    "Things people do drunk they wouldn't do sober",
    "Celebrity DJs",
    "Types of shots",
    "Things you'd find at a house party",
    "Brands of vodka",
    "Things you regret buying",
    "Cartoon characters",
    "Pizza toppings",
    "Things you'd do if you were invisible",
    "Apps on your phone",
    "Things that come in pairs",
    "One-hit wonders",
    "Excuses for not texting back",
    "Breakfast cereals",
    "Things you'd bring to a desert island",
    "Types of cheese",
    "Things people lie about on dating apps",
    "Movie villains",
    "Things that smell bad",
    "Things you'd find in a college dorm",
    "Types of pasta",
    "Things you shouldn't do on a first date",
    "Reality TV shows",
    "Things you'd buy if you won the lottery",
    "Excuses for leaving a party early",
    "Things you'd never admit to your parents",
    "90s/2000s TV shows",
    "Things that are more fun when you're drunk",
    "Famous movie quotes",
    "Things you'd find in a fridge at 3am",
    "Things people say when they're lying",
    "Video games",
    "Things that give you the ick",
    "Things you'd bring to a potluck",
    "Reasons people cry",
    "Things that sound dirty but aren't",
    "Things you shouldn't do while driving",
]

# ─── Trivia ──────────────────────────────────────────────────────────────────

TRIVIA = [
    {"q": "What is the most popular cocktail in the world?", "options": ["Margarita", "Old Fashioned", "Mojito", "Martini"], "answer": 0},
    {"q": "Which country drinks the most beer per capita?", "options": ["Germany", "Czech Republic", "Ireland", "USA"], "answer": 1},
    {"q": "What is tequila made from?", "options": ["Corn", "Blue agave", "Sugarcane", "Potatoes"], "answer": 1},
    {"q": "What does IPA stand for?", "options": ["International Pale Ale", "India Pale Ale", "Irish Pale Ale", "Italian Pale Ale"], "answer": 1},
    {"q": "Which fruit is used to make a traditional daiquiri?", "options": ["Mango", "Strawberry", "Lime", "Pineapple"], "answer": 2},
    {"q": "What is the fear of alcohol called?", "options": ["Methyphobia", "Alcoholophobia", "Vinophobia", "Potophobia"], "answer": 0},
    {"q": "How many standard drinks are in a bottle of wine?", "options": ["3", "5", "7", "4"], "answer": 1},
    {"q": "What ingredient makes a Moscow Mule unique?", "options": ["Lime juice", "Ginger beer", "Vodka", "Mint"], "answer": 1},
    {"q": "Which country is famous for sake?", "options": ["China", "Korea", "Japan", "Thailand"], "answer": 2},
    {"q": "What does 'ABV' stand for?", "options": ["Alcohol Before Volume", "Alcohol By Volume", "Always Buy Vodka", "Ale Brewed Varietal"], "answer": 1},
    {"q": "What is the main ingredient in bourbon?", "options": ["Wheat", "Rye", "Corn", "Barley"], "answer": 2},
    {"q": "A 'flight' in bar terms refers to what?", "options": ["A drinking contest", "A sampler of drinks", "A type of glass", "Leaving without paying"], "answer": 1},
    {"q": "What gives gin its distinctive flavor?", "options": ["Hops", "Juniper berries", "Coriander", "Pine needles"], "answer": 1},
    {"q": "What cocktail is James Bond famous for ordering?", "options": ["Manhattan", "Martini", "Old Fashioned", "Negroni"], "answer": 1},
    {"q": "Which beer brand uses the slogan 'The King of Beers'?", "options": ["Heineken", "Budweiser", "Corona", "Miller"], "answer": 1},
    {"q": "What is a 'jigger' used for in bartending?", "options": ["Stirring", "Measuring", "Straining", "Shaking"], "answer": 1},
    {"q": "What country did champagne originate from?", "options": ["Italy", "Spain", "France", "Germany"], "answer": 2},
    {"q": "What is absinthe traditionally nicknamed?", "options": ["The Green Fairy", "The Black Mamba", "The Devil's Drink", "The Blue Moon"], "answer": 0},
    {"q": "What type of alcohol is in a Pina Colada?", "options": ["Vodka", "Tequila", "Rum", "Gin"], "answer": 2},
    {"q": "What does 'on the rocks' mean?", "options": ["Blended with ice", "Served with ice", "No ice", "Warm"], "answer": 1},
    {"q": "Which country produces the most wine?", "options": ["France", "Italy", "Spain", "USA"], "answer": 1},
    {"q": "What is the main spirit in a Cosmopolitan?", "options": ["Gin", "Rum", "Vodka", "Tequila"], "answer": 2},
    {"q": "What color is Midori liqueur?", "options": ["Blue", "Red", "Green", "Yellow"], "answer": 2},
    {"q": "How many bottles of champagne in a Nebuchadnezzar?", "options": ["6", "10", "15", "20"], "answer": 3},
    {"q": "What is a 'boilermaker'?", "options": ["A type of still", "Beer with a whiskey shot", "A heated cocktail", "A beer bong"], "answer": 1},
    {"q": "What's the national drink of Brazil?", "options": ["Caipirinha", "Mojito", "Pisco Sour", "Daiquiri"], "answer": 0},
    {"q": "What does 'proof' measure in alcohol?", "options": ["Color intensity", "Double the ABV percentage", "Sugar content", "Fermentation time"], "answer": 1},
    {"q": "Which cocktail is typically served in a copper mug?", "options": ["Mint Julep", "Moscow Mule", "Dark and Stormy", "Whiskey Sour"], "answer": 1},
    {"q": "What is the oldest known alcoholic beverage?", "options": ["Wine", "Beer", "Mead", "Sake"], "answer": 2},
    {"q": "What does 'neat' mean when ordering a drink?", "options": ["With ice", "Room temperature, no mixer", "Shaken", "With a splash of water"], "answer": 1},
    {"q": "Which country invented vodka?", "options": ["Russia", "Poland", "Both claim it", "Sweden"], "answer": 2},
    {"q": "What is the worm in a bottle of mezcal actually?", "options": ["A worm", "A moth larva", "A beetle", "Decorative plastic"], "answer": 1},
    {"q": "What's the most consumed alcoholic drink worldwide?", "options": ["Wine", "Beer", "Vodka", "Whiskey"], "answer": 1},
    {"q": "What flavor is Fireball whiskey?", "options": ["Cherry", "Cinnamon", "Vanilla", "Caramel"], "answer": 1},
    {"q": "What cocktail is made with rum, coconut cream, and pineapple?", "options": ["Mai Tai", "Zombie", "Pina Colada", "Blue Lagoon"], "answer": 2},
    {"q": "How many glasses of champagne are in a standard bottle?", "options": ["4", "6", "8", "10"], "answer": 1},
    {"q": "What's the main ingredient in a Bloody Mary?", "options": ["Cranberry juice", "Orange juice", "Tomato juice", "Grapefruit juice"], "answer": 2},
    {"q": "What does 'single malt' mean in whiskey?", "options": ["One distillery", "One type of grain", "One barrel", "One year of aging"], "answer": 0},
    {"q": "Which beer style originated in Germany and translates to 'storage'?", "options": ["Pilsner", "Lager", "Stout", "Porter"], "answer": 1},
]

# ─── Hot Takes ───────────────────────────────────────────────────────────────

HOT_TAKES = [
    "Pineapple absolutely belongs on pizza",
    "Breakfast for dinner is better than dinner for dinner",
    "Dogs are overrated — cats are superior",
    "Social media has made the world a worse place",
    "Cold pizza is better than hot pizza",
    "It's okay to recline your seat on an airplane",
    "Ketchup on eggs is completely acceptable",
    "Beyonce is overrated",
    "Working from home is better than working in an office",
    "The toilet paper should go over, not under — always",
    "Water is not wet",
    "A hot dog IS a sandwich",
    "Tipping culture has gone too far",
    "Cereal is a soup",
    "It's fine to wear socks with sandals",
    "The book is NOT always better than the movie",
    "Astrology is complete nonsense",
    "GIF is pronounced with a hard G — always",
    "Naps are a waste of time",
    "The person who suggests the restaurant should pay",
    "It's okay to text 'k'",
    "Reality TV is actually good entertainment",
    "Brunch is overrated and overpriced",
    "Dark chocolate is superior to milk chocolate",
    "You should shower at night, not in the morning",
    "Being early is just as rude as being late",
    "Ranch goes on everything",
    "Summer is the worst season",
    "New Year's Eve is the most overrated holiday",
    "Sparkling water is just angry water and it's gross",
    "Reclining your airplane seat is an act of war",
    "Oat milk is better than regular milk",
    "It's never too early for Christmas music",
    "Double texting is not desperate",
    "Sleeping with socks on is psychopath behavior",
    "The office thermostat should always be set to cold",
    "Crocs are actually stylish now",
    "It's okay to eat dessert before dinner",
    "People who don't use turn signals should lose their license",
    "The 5-second rule is scientifically valid",
    "Unplugging from social media for a month would ruin most people",
    "Peanut butter and jelly is the greatest sandwich ever made",
    "Being overdressed is always better than being underdressed",
    "Group chats are more stressful than useful",
]

# ─── Taboo ───────────────────────────────────────────────────────────────────

TABOO_WORDS = [
    {"word": "Hangover", "forbidden": ["Drink", "Morning", "Headache", "Alcohol", "Party"]},
    {"word": "Karaoke", "forbidden": ["Sing", "Song", "Microphone", "Bar", "Music"]},
    {"word": "Selfie", "forbidden": ["Photo", "Camera", "Phone", "Picture", "Snap"]},
    {"word": "Netflix", "forbidden": ["Stream", "Watch", "Show", "Movie", "Chill"]},
    {"word": "Tinder", "forbidden": ["Swipe", "Date", "Match", "App", "Love"]},
    {"word": "Pizza", "forbidden": ["Cheese", "Slice", "Delivery", "Italian", "Pepperoni"]},
    {"word": "Uber", "forbidden": ["Ride", "Car", "Driver", "App", "Taxi"]},
    {"word": "Tattoo", "forbidden": ["Ink", "Skin", "Needle", "Body", "Permanent"]},
    {"word": "Beach", "forbidden": ["Sand", "Ocean", "Water", "Sun", "Wave"]},
    {"word": "Meme", "forbidden": ["Funny", "Internet", "Picture", "Viral", "Share"]},
    {"word": "Brunch", "forbidden": ["Breakfast", "Lunch", "Morning", "Eggs", "Mimosa"]},
    {"word": "Gym", "forbidden": ["Exercise", "Workout", "Lift", "Fit", "Muscle"]},
    {"word": "Snapchat", "forbidden": ["Snap", "Photo", "Filter", "Story", "Send"]},
    {"word": "Coachella", "forbidden": ["Music", "Festival", "Desert", "California", "Concert"]},
    {"word": "Avocado", "forbidden": ["Green", "Guacamole", "Toast", "Fruit", "Mexican"]},
    {"word": "Champagne", "forbidden": ["Bubbles", "Wine", "Celebrate", "Toast", "French"]},
    {"word": "Podcast", "forbidden": ["Listen", "Audio", "Episode", "Show", "Talk"]},
    {"word": "Road Trip", "forbidden": ["Drive", "Car", "Travel", "Highway", "Journey"]},
    {"word": "Halloween", "forbidden": ["Costume", "Scary", "October", "Candy", "Pumpkin"]},
    {"word": "TikTok", "forbidden": ["Video", "Dance", "App", "Short", "Viral"]},
    {"word": "Margarita", "forbidden": ["Tequila", "Salt", "Lime", "Cocktail", "Mexican"]},
    {"word": "Sushi", "forbidden": ["Fish", "Rice", "Japanese", "Roll", "Raw"]},
    {"word": "Concert", "forbidden": ["Music", "Band", "Live", "Stage", "Tickets"]},
    {"word": "Sunburn", "forbidden": ["Sun", "Red", "Skin", "Burn", "Beach"]},
    {"word": "Gossip", "forbidden": ["Talk", "Secret", "Rumor", "Tell", "Drama"]},
    {"word": "Hangout", "forbidden": ["Friends", "Meet", "Chill", "Together", "Fun"]},
    {"word": "Influencer", "forbidden": ["Social", "Follow", "Famous", "Instagram", "Brand"]},
    {"word": "Karate", "forbidden": ["Martial", "Kick", "Belt", "Fight", "Art"]},
    {"word": "Barbecue", "forbidden": ["Grill", "Meat", "Cook", "Outside", "Summer"]},
    {"word": "Whiskey", "forbidden": ["Bourbon", "Drink", "Alcohol", "Shot", "Barrel"]},
    {"word": "Uber Eats", "forbidden": ["Delivery", "Food", "App", "Order", "Driver"]},
    {"word": "Yoga", "forbidden": ["Stretch", "Pose", "Meditation", "Flexible", "Mat"]},
    {"word": "Bitcoin", "forbidden": ["Crypto", "Money", "Digital", "Mine", "Coin"]},
    {"word": "Escape Room", "forbidden": ["Puzzle", "Lock", "Clue", "Trapped", "Solve"]},
    {"word": "Airbnb", "forbidden": ["Rent", "House", "Travel", "Stay", "Hotel"]},
    {"word": "Binge Watch", "forbidden": ["TV", "Show", "Marathon", "Netflix", "Episodes"]},
    {"word": "Photobomb", "forbidden": ["Photo", "Background", "Ruin", "Picture", "Behind"]},
    {"word": "Black Friday", "forbidden": ["Sale", "Shop", "November", "Deal", "Discount"]},
    {"word": "Karaoke", "forbidden": ["Sing", "Song", "Microphone", "Bar", "Lyrics"]},
    {"word": "Jetlag", "forbidden": ["Tired", "Travel", "Sleep", "Time", "Fly"]},
    {"word": "Potluck", "forbidden": ["Food", "Bring", "Party", "Share", "Dish"]},
    {"word": "Ghosting", "forbidden": ["Ignore", "Text", "Disappear", "Reply", "Date"]},
    {"word": "Influencer", "forbidden": ["Social", "Famous", "Follow", "Post", "Brand"]},
    {"word": "Hangover Cure", "forbidden": ["Drink", "Morning", "Water", "Food", "Headache"]},
]

# ─── Two Truths and a Lie — starter prompts ─────────────────────────────────

TWO_TRUTHS_PROMPTS = [
    "Think of two TRUE things and one LIE about your childhood.",
    "Think of two TRUE things and one LIE about your love life.",
    "Think of two TRUE things and one LIE about your worst habits.",
    "Think of two TRUE things and one LIE about embarrassing moments.",
    "Think of two TRUE things and one LIE about things you've eaten.",
    "Think of two TRUE things and one LIE about your job/school.",
    "Think of two TRUE things and one LIE about your travels.",
    "Think of two TRUE things and one LIE about your biggest fears.",
    "Think of two TRUE things and one LIE about your guilty pleasures.",
    "Think of two TRUE things and one LIE about things you've broken.",
    "Think of two TRUE things and one LIE about your teenage years.",
    "Think of two TRUE things and one LIE about your family.",
    "Think of two TRUE things and one LIE about concerts you've attended.",
    "Think of two TRUE things and one LIE about your phone habits.",
    "Think of two TRUE things and one LIE about things you've lost.",
    "Think of two TRUE things and one LIE about your worst dates.",
    "Think of two TRUE things and one LIE about your party stories.",
    "Think of two TRUE things and one LIE about your cooking disasters.",
    "Think of two TRUE things and one LIE about things you've stolen (even small things).",
    "Think of two TRUE things and one LIE about your hidden talents.",
    "Think of two TRUE things and one LIE about your celebrity encounters.",
    "Think of two TRUE things and one LIE about your worst injuries.",
    "Think of two TRUE things and one LIE about your social media habits.",
    "Think of two TRUE things and one LIE about your music taste.",
    "Think of two TRUE things and one LIE about your roommate experiences.",
]

# ─── Rhyme Time ──────────────────────────────────────────────────────────────

RHYME_STARTERS = [
    "cat", "blue", "night", "fun", "beer", "cake", "dance", "gold",
    "ring", "star", "light", "smoke", "drink", "lime", "beat", "chill",
    "rock", "day", "green", "hot", "cool", "fire", "rain", "high",
    "ride", "game", "fly", "loud", "dream", "wine",
    "shake", "toast", "glow", "space", "crown", "phone",
    "jive", "spark", "moon", "trip", "bass", "vibe",
    "trick", "flame", "flow", "drift", "rush", "jam",
]

# ─── Word Association ────────────────────────────────────────────────────────

WORD_ASSOCIATION_STARTERS = [
    "Party", "Drunk", "Shot", "Music", "Dance", "Love", "Beach",
    "Money", "Sleep", "Smoke", "Pizza", "Regret", "Selfie", "Kiss",
    "Secret", "Wild", "Midnight", "Vegas", "Dare", "Crazy",
    "Guilty", "Rumor", "Cheers", "Chaos", "Lit",
    "Hangover", "Karaoke", "Confession", "Tequila", "Drama",
    "Midnight", "Awkward", "Hookup", "Scandal", "Cringe",
    "Savage", "Vibes", "Toxic", "Clout", "Ghosted",
]


# ═══════════════════════════════════════════════════════════════════════════════
# 18+ / SPICY MODE CONTENT
# ═══════════════════════════════════════════════════════════════════════════════

TRUTHS_SPICY = [
    "What's the wildest thing you've done in someone else's bed?",
    "Have you ever hooked up with someone in this room? Spill.",
    "What's your most embarrassing bedroom moment?",
    "What's the kinkiest thing on your bucket list?",
    "Have you ever sent a nude to the wrong person?",
    "What's the weirdest place you've ever hooked up?",
    "Who in this room would you most want to see naked?",
    "What's your guilty pleasure when it comes to adult content?",
    "Have you ever faked it? Be honest.",
    "What's the most scandalous DM in your inbox right now?",
    "What's your body count? And no, we don't believe the first number.",
    "Who was your worst hookup and why?",
    "Have you ever been caught in the act? By who?",
    "What's the longest you've ever gone without sex?",
    "What's a turn-on you're embarrassed to admit?",
    "Have you ever hooked up with a friend's ex?",
    "What's the most desperate thing you've done to get laid?",
    "Have you ever had a one-night stand you regretted immediately?",
    "What's the hottest dream you've ever had about someone here?",
    "What's the most risqué photo still on your phone right now?",
    "Have you ever used a dating app while in a relationship?",
    "What's the biggest lie you've told to get someone in bed?",
    "Have you ever done the walk of shame in broad daylight?",
    "What's the naughtiest text you've ever sent?",
    "Have you ever had a crush on a friend's parent?",
    "What's the most embarrassing thing you've Googled about sex?",
    "Have you ever been caught watching adult content?",
    "What's the craziest thing an ex has asked you to do in bed?",
    "Have you ever made out with someone just to make someone else jealous?",
    "What's the most NSFW thing in your search history right now?",
    "What's the craziest place you've ever been caught making out?",
    "Have you ever had a sugar daddy/mommy or considered it?",
    "What's the most embarrassing thing that's happened during sex?",
    "Have you ever used someone's Netflix just to get them to come over?",
    "Who in this room would you swipe right on?",
    "What's the raunchiest thing on your camera roll right now?",
    "Have you ever been attracted to a friend's sibling?",
    "What's the most regrettable thing you've done at a party?",
    "Have you ever lied about your body count? By how much?",
    "What's the most scandalous outfit you've ever worn out?",
    "Have you ever had a crush on someone in a relationship? Did you act on it?",
    "What's the spiciest thing you've sent over text that you'd die if it leaked?",
    "Have you ever pretended to be single when you weren't?",
    "What's a fantasy you've never told anyone about?",
]

DARES_SPICY = [
    "Show the group your most scandalous photo (that you're willing to share).",
    "Send a flirty text to the last person you texted. Screenshot it.",
    "Let the group read your last 5 DMs out loud.",
    "Give someone in the room a lap dance for 15 seconds or drink 3 times.",
    "Demonstrate your best O-face for the group.",
    "Let someone write anything on your body with a marker. Keep it for the night.",
    "Call your ex and tell them you miss them. Speaker on.",
    "Post 'I'm horny' on your social media story for 30 minutes or drink 5 times.",
    "Whisper something dirty in the ear of the person to your left.",
    "Take off one piece of clothing of the group's choice (or drink 3 times).",
    "Give a dramatic, sensual reading of the last text you received.",
    "Let the group go through your dating app and swipe for 1 minute.",
    "Do your sexiest walk across the room.",
    "Give a 30-second seductive dance to the person the group picks.",
    "Text your crush something bold. Show everyone. Drink regardless.",
    "Describe your ideal hookup scenario in vivid detail.",
    "Let the group compose and send a thirst trap DM from your account.",
    "Sit on the lap of the person to your right for the next round.",
    "Suck on your finger seductively for 10 seconds.",
    "Motorboat a pillow while making eye contact with someone.",
    "Give the person across from you bedroom eyes for 20 seconds straight.",
    "Tell the group your most NSFW fantasy.",
    "Let the group pick a contact — send them '😏 wyd tonight?'",
    "Do 5 body rolls. Drink for each one the group says was bad.",
    "Share the raunchiest meme in your camera roll.",
    "Let the group go through your 'Recently Deleted' photos. Drink for every NSFW one.",
    "Recreate your best thirst trap pose. Group rates 1-10.",
    "Text 'I had a dream about you last night...' to the 5th contact in your recents.",
    "Let the group compose a spicy bio for your dating profile.",
    "Do your best impression of someone being seduced in a movie.",
    "Let the person across from you draw something on your arm with a marker.",
    "Give your best pick-up line to each person in the room. Drink if anyone cringes.",
    "Play a voice note from your phone out loud. If you refuse, drink 4 times.",
    "Describe your celebrity crush in uncomfortably specific detail.",
    "Let the group pick someone — you have to slow dance with them for 30 seconds.",
    "Rate everyone in the room on a hotness scale 1-10. Out loud.",
    "Show your most-used dating app or admit you deleted it.",
    "Do a dramatic reading of the worst pickup line you've ever received.",
    "Let the group change your dating app bio for 24 hours. Or drink 5 times.",
]

NEVER_HAVE_I_EVER_SPICY = [
    "Never have I ever had a threesome",
    "Never have I ever hooked up with a coworker",
    "Never have I ever sent a nude",
    "Never have I ever been to a strip club",
    "Never have I ever slept with someone on the first date",
    "Never have I ever had sex in a car",
    "Never have I ever watched adult content with someone else",
    "Never have I ever been friends with benefits",
    "Never have I ever had a one-night stand",
    "Never have I ever sexted a stranger",
    "Never have I ever hooked up with someone twice my age",
    "Never have I ever used a toy in the bedroom",
    "Never have I ever had sex in a public place",
    "Never have I ever gone commando on a night out",
    "Never have I ever faked an orgasm",
    "Never have I ever made a sex tape",
    "Never have I ever been skinny dipping with a crush",
    "Never have I ever woken up naked and not remembered why",
    "Never have I ever had a booty call at 3am",
    "Never have I ever kissed someone of the same gender",
    "Never have I ever used a dating app just for hookups",
    "Never have I ever done body shots off someone",
    "Never have I ever had sex while someone was in the next room",
    "Never have I ever received a dick pic I didn't ask for",
    "Never have I ever hooked up at a house party",
    "Never have I ever had a friends-with-benefits situation go wrong",
    "Never have I ever had phone sex",
    "Never have I ever role-played in the bedroom",
    "Never have I ever been in a hot tub with someone and things got heated",
    "Never have I ever been handcuffed (in or out of the bedroom)",
    "Never have I ever been caught hooking up in a car",
    "Never have I ever used whipped cream in a non-food way",
    "Never have I ever sent a risky photo to the wrong person",
    "Never have I ever lied about being good in bed",
    "Never have I ever had a crush on my best friend's partner",
    "Never have I ever pretended to be asleep to avoid sex",
    "Never have I ever hooked up with someone I met that same day",
    "Never have I ever made out in a bathroom at a party",
    "Never have I ever gone back to an ex just for the physical stuff",
    "Never have I ever been walked in on during a video call",
    "Never have I ever had a wardrobe malfunction that showed way too much",
    "Never have I ever said someone else's name during an intimate moment",
    "Never have I ever been the other person in someone's relationship",
    "Never have I ever flirted with someone to get free drinks",
]

WOULD_YOU_RATHER_SPICY = [
    ("Give up sex for a year", "Give up your phone for a year"),
    ("Have your parents walk in on you", "Walk in on your parents"),
    ("Only have drunk sex for the rest of your life", "Only have sober sex"),
    ("Have everyone know your body count", "Have everyone know your kinks"),
    ("Sleep with your celebrity crush but nobody believes you", "Never sleep with them but everyone thinks you did"),
    ("Have amazing sex once a year", "Have mediocre sex every day"),
    ("Only hook up in silence", "Only hook up while loud music plays"),
    ("Accidentally like your ex's thirst trap", "Accidentally send a nude to your boss"),
    ("Have a partner who's boring in bed but amazing everywhere else", "Amazing in bed but boring everywhere else"),
    ("Never orgasm again", "Orgasm every time someone shakes your hand"),
    ("Be known for being great in bed", "Be known for being great at cooking"),
    ("Have your search history exposed", "Have your DMs exposed"),
    ("Hook up with someone who talks dirty the entire time", "Hook up with someone completely silent"),
    ("Date someone with no lips", "Date someone with no eyebrows"),
    ("Have sex with the lights on forever", "Have sex with the lights off forever"),
    ("Walk in on your best friend", "Have your best friend walk in on you"),
    ("Have your one-night stand follow you on all socials", "Have your parents follow all your hookups on social media"),
    ("Get caught sexting by your boss", "Get caught watching porn by your partner"),
    ("Only ever do it in a twin bed", "Only ever do it standing up"),
    ("Have your partner narrate everything during sex", "Have a laugh track play during sex"),
    ("Accidentally moan in a work meeting", "Accidentally send a spicy text to your family group chat"),
    ("Have your hookup history on a billboard in your town", "Have your search history on a billboard"),
    ("Only hook up to the soundtrack of The Lion King", "Only hook up while a nature documentary plays"),
    ("Have your ex write a review of you on Google", "Have your current crush read all your old DMs about them"),
    ("Never be able to kiss again", "Never be able to hug again"),
    ("Date someone who's a 10 but terrible in bed", "Date someone who's a 5 but incredible in bed"),
    ("Have your parents find your hidden folder", "Have your boss find your dating profile"),
    ("Always have to make the first move", "Never be able to make the first move"),
    ("Have amazing chemistry but awful conversations", "Have amazing conversations but zero chemistry"),
]

MOST_LIKELY_TO_SPICY = [
    "Most likely to have a secret OnlyFans",
    "Most likely to hook up with someone tonight",
    "Most likely to be into some weird kink",
    "Most likely to sext in a meeting",
    "Most likely to have a body count they'll never admit",
    "Most likely to sleep with someone for free food",
    "Most likely to get caught watching porn at work",
    "Most likely to propose a threesome",
    "Most likely to have hooked up with someone in this room",
    "Most likely to slide into a celebrity's DMs",
    "Most likely to get caught having sex in public",
    "Most likely to lie about their body count",
    "Most likely to have had a scandalous hookup story",
    "Most likely to send an unsolicited thirst trap",
    "Most likely to date someone just for their looks",
    "Most likely to cheat in a game of strip poker",
    "Most likely to wake up in a stranger's bed",
    "Most likely to be freaky in the sheets but a saint in the streets",
    "Most likely to have a secret fetish",
    "Most likely to have the wildest browser history",
    "Most likely to be a screamer",
    "Most likely to get caught moaning someone's name",
    "Most likely to accidentally send a sext to the group chat",
    "Most likely to go home with the bartender",
    "Most likely to have a hookup they'll take to the grave",
    "Most likely to have a whole other persona on their finsta",
    "Most likely to get caught flirting with someone at a wedding",
    "Most likely to have an embarrassing tattoo they regret",
    "Most likely to be the worst texter in a situationship",
    "Most likely to use a cheesy pickup line and somehow make it work",
    "Most likely to accidentally broadcast something embarrassing on their story",
    "Most likely to have the most unhinged notes app confessions",
    "Most likely to hook up with someone at a reunion",
    "Most likely to be secretly writing spicy fan fiction",
    "Most likely to get caught staring at someone's body",
]

CATEGORIES_SPICY = [
    "Sex positions",
    "Things you say in bed",
    "Dating red flags that you'd still ignore if they were hot",
    "Excuses for a booty call",
    "Things you'd find in a sex shop",
    "Euphemisms for hooking up",
    "Things you should never say during sex",
    "Types of lingerie",
    "Things that are sexy on screen but awkward in real life",
    "Reasons to break up (bedroom-related)",
    "Dirty pickup lines",
    "Things you'd do for a million dollars (NSFW edition)",
    "Body parts people find attractive",
    "Things you'd whisper in someone's ear",
    "Adult film titles (made up)",
    "Things that kill the mood",
    "Celebrities people thirst over",
    "Things people lie about in bed",
    "Types of kisses",
    "Sounds you hear through thin apartment walls",
    "Things you'd never tell your parents you've done",
    "Worst places to get caught making out",
    "Things that are inappropriately shaped",
    "Embarrassing things you've Googled late at night",
    "Things people do in the shower that they won't admit",
    "Red flags in someone's bedroom",
    "Things that are hot in theory but terrible in practice",
    "Nicknames for body parts",
    "Things you shouldn't say on a first date but want to",
]

HOT_TAKES_SPICY = [
    "Size absolutely matters",
    "Cuddling after sex is non-negotiable",
    "Morning sex is better than nighttime sex",
    "It's okay to fake an orgasm to spare feelings",
    "Shower sex is overrated and dangerous",
    "Sexting is a skill and most people are bad at it",
    "Friends with benefits always catches feelings",
    "Body count shouldn't matter in a relationship",
    "Drunk sex is never as good as people think",
    "It's okay to watch porn in a relationship",
    "One-night stands are empowering, not shameful",
    "Spooning always leads to forking",
    "People who say they never watch porn are liars",
    "Three-date rule before sleeping together is outdated",
    "Everyone has a type and pretending you don't is lying",
    "Open relationships can work",
    "Sexiness is more about confidence than looks",
    "Bad sex is a dealbreaker for a relationship",
    "Kissing is more intimate than sex",
    "People who brag about their sex life are usually bad in bed",
    "Situationships are just relationships for cowards",
    "You can tell someone's bedroom skills by how they dance",
    "Jealousy is actually kind of attractive in small doses",
    "Your ex's new partner is always uglier — it's science",
    "Everyone has a 'hall pass' list and that's completely normal",
    "Makeup sex is the best kind of sex",
    "Drunk confessions are always the truth",
    "Being left on read is worse than being rejected in person",
    "Love at first sight is just lust with good marketing",
]

TABOO_WORDS_SPICY = [
    {"word": "Tinder", "forbidden": ["Swipe", "App", "Date", "Match", "Hook up"]},
    {"word": "Strip Club", "forbidden": ["Dance", "Pole", "Naked", "Money", "Bar"]},
    {"word": "Handcuffs", "forbidden": ["Police", "Metal", "Wrist", "Lock", "Kinky"]},
    {"word": "Skinny Dipping", "forbidden": ["Naked", "Swim", "Pool", "Water", "Night"]},
    {"word": "Walk of Shame", "forbidden": ["Morning", "Walk", "Night", "Home", "Party"]},
    {"word": "Booty Call", "forbidden": ["Late", "Night", "Text", "Hook up", "Phone"]},
    {"word": "Lingerie", "forbidden": ["Underwear", "Sexy", "Lace", "Victoria", "Wear"]},
    {"word": "Hickey", "forbidden": ["Neck", "Mark", "Kiss", "Suck", "Bruise"]},
    {"word": "Pickup Line", "forbidden": ["Flirt", "Bar", "Cheesy", "Talk", "Girl"]},
    {"word": "Body Shots", "forbidden": ["Drink", "Salt", "Belly", "Lick", "Tequila"]},
    {"word": "Vibrator", "forbidden": ["Buzz", "Toy", "Battery", "Pleasure", "Adult"]},
    {"word": "Blindfold", "forbidden": ["Eyes", "See", "Cover", "Dark", "Surprise"]},
    {"word": "Friends with Benefits", "forbidden": ["Friend", "Sex", "Casual", "No strings", "Relationship"]},
    {"word": "Make Out", "forbidden": ["Kiss", "Lips", "Tongue", "Touch", "Snog"]},
    {"word": "Bedroom Eyes", "forbidden": ["Look", "Sexy", "Stare", "Flirt", "Seductive"]},
    {"word": "One Night Stand", "forbidden": ["Hook up", "Night", "Stranger", "Leave", "Morning"]},
    {"word": "Safeword", "forbidden": ["Stop", "Kinky", "Boundary", "Word", "BDSM"]},
    {"word": "Thirst Trap", "forbidden": ["Photo", "Sexy", "Instagram", "Attention", "Hot"]},
    {"word": "Walk of Fame", "forbidden": ["Hollywood", "Star", "Walk", "Celebrity", "Sidewalk"]},
    {"word": "Netflix and Chill", "forbidden": ["Watch", "Movie", "Relax", "Hook up", "Date"]},
    {"word": "Situationship", "forbidden": ["Relationship", "Dating", "Casual", "Complicated", "Label"]},
    {"word": "Walk of Shame", "forbidden": ["Morning", "Party", "Night", "Clothes", "Home"]},
    {"word": "Sugar Daddy", "forbidden": ["Money", "Old", "Rich", "Pay", "Spoil"]},
    {"word": "Love Bite", "forbidden": ["Neck", "Mark", "Kiss", "Hickey", "Suck"]},
    {"word": "Catfish", "forbidden": ["Fake", "Online", "Photo", "Lie", "Profile"]},
    {"word": "Rebound", "forbidden": ["Ex", "Breakup", "New", "Relationship", "Quick"]},
    {"word": "Pillow Talk", "forbidden": ["Bed", "Talk", "After", "Night", "Cuddle"]},
    {"word": "Skinny Dipping", "forbidden": ["Naked", "Swim", "Water", "Night", "Pool"]},
    {"word": "Wingman", "forbidden": ["Friend", "Help", "Bar", "Talk", "Approach"]},
]

TWO_TRUTHS_PROMPTS_SPICY = [
    "Think of two TRUE things and one LIE about your hookup history.",
    "Think of two TRUE things and one LIE about your wildest night out.",
    "Think of two TRUE things and one LIE about your dating life.",
    "Think of two TRUE things and one LIE about things you've done in bed.",
    "Think of two TRUE things and one LIE about your exes.",
    "Think of two TRUE things and one LIE about your body count timeline.",
    "Think of two TRUE things and one LIE about your DMs.",
    "Think of two TRUE things and one LIE about your most scandalous moment.",
    "Think of two TRUE things and one LIE about your kinks/fantasies.",
    "Think of two TRUE things and one LIE about your drunk hookup adventures.",
    "Think of two TRUE things and one LIE about awkward sexual experiences.",
    "Think of two TRUE things and one LIE about your dating app history.",
    "Think of two TRUE things and one LIE about your secret crushes.",
    "Think of two TRUE things and one LIE about things you've done for an ex.",
    "Think of two TRUE things and one LIE about your naughtiest adventures.",
    "Think of two TRUE things and one LIE about your situationships.",
    "Think of two TRUE things and one LIE about embarrassing things you've said during intimacy.",
    "Think of two TRUE things and one LIE about your dating app disasters.",
    "Think of two TRUE things and one LIE about your most reckless nights.",
    "Think of two TRUE things and one LIE about things you've done to impress a crush.",
]

RHYME_STARTERS_SPICY = [
    "bed", "kiss", "hot", "strip", "lick", "ride", "tease", "moan",
    "lust", "bare", "thrust", "grind", "whip", "sin", "flesh",
    "blush", "tight", "naughty", "thong", "spank", "lips", "heat",
    "stroke", "bite", "bang", "drip", "suck", "peak", "raw", "wild",
    "touch", "sweat", "cream", "wet", "grip", "slip", "buzz",
    "crave", "thick", "steam", "pulse", "dark", "deep", "push",
]

WORD_ASSOCIATION_STARTERS_SPICY = [
    "Bedroom", "Handcuffs", "Whipped cream", "Blindfold", "Desire",
    "Forbidden", "Temptation", "Seduction", "Leather", "Pleasure",
    "Fantasy", "Naughty", "Climax", "Lust", "Passion",
    "Tease", "Submission", "Tension", "Explicit", "Afterglow",
    "Scandal", "Taboo", "Appetite", "Silk", "Surrender",
    "Wet", "Dominate", "Strip", "Moan", "Choke",
    "Worship", "Control", "Obsession", "Hunger", "Ravish",
]

# ─── Helper to get random items without immediate repeats ────────────────────

class ShuffledDeck:
    """Draw items from a list without repeating until all are used."""

    def __init__(self, items: list[Any]) -> None:
        self._items = list(items)
        self._deck: list[Any] = []

    def draw(self) -> Any:
        if not self._deck:
            self._deck = list(self._items)
            random.shuffle(self._deck)
        return self._deck.pop()

    def draw_n(self, n: int) -> list[Any]:
        return [self.draw() for _ in range(n)]
